/voice_assistant_node:
  ros__parameters:
    exit_cmd_options: ['bye', 'bubye', 'adios', 'ciao', 'no thanks', 'no thank you', 'see you', 'take care']
    speech_recognizer:
      energy_threshold: 200 # can be set between 50-5000. Increase this number if ambient noise is high
      mic_device_index: 13
      phrase_time_limit: 6 # maximum number of seconds speech recognizer will allow a phrase to continue before stopping and returning the part of the phrase processed before the time limit was reached. The resulting audio will be the phrase cut off at the time limit. If ``phrase_timeout`` is ``None``, there will be no phrase time limit.
      timeout: 10 # maximum number of seconds speech recognizer will wait for a phrase to start before giving up. If ``timeout`` is ``None``, there will be no wait timeout.
      use_whisper: true # uses OpenAI transcriber
    text_to_speech_engine: elevenlabs # Options are: pyttsx3, elevenlabs. Elevenlabs is more realistic
    use_sim_time: false

/voice_arduino_bridge_node:
  ros__parameters:
    test_voice_only: True # if actually connect with arduino and runservos or only test voice interaction
    snack_options: ['chips', 'chocolate', 'candies', 'nuts'] #TODO: handle chocolates or candy
    snack_quantity: [5, 5, 5, 5] # number of snacks available for each of the snack_options
    snack2servos_map: [1, 2, 3, 4]
    