postfix: ${..postfix}
sequence: ${..sequence}
base_path: "/home/trailbot/RAG/results/${sequence}"
# sequence: "103"

instruction_path: "/home/trailbot/RAG/results/${sequence}/instructions/instruction.json"
latest_idx_path: "/home/trailbot/RAG/results/${sequence}/latest_frame/${postfix}/latest_frame.txt"
rgb_folder: "/home/trailbot/RAG/results/${sequence}/capture/${postfix}"
label_folder: "/home/trailbot/RAG/results/${sequence}/labels"

retrieve_folder: "/home/trailbot/RAG/results/${sequence}/search_DB/${postfix}"
retrieve_annotated_folder: "/home/trailbot/RAG/results/${sequence}/images/${postfix}"
cot_log_folder: "/home/trailbot/RAG/results/${sequence}/cot_log/${postfix}"

semantic_folder: "/home/trailbot/RAG/results/${sequence}/seg_map/${postfix}"
occupancy_folder: "/home/trailbot/RAG/results/${sequence}/occ_map/${postfix}"
cost_folder: "/home/trailbot/RAG/results/${sequence}/cost_map/${postfix}"

fallback_image_path: "/home/opennav_mem/star/docs/fallback_image.png"
update_flag_path: "/home/trailbot/RAG/results/${sequence}/update/update.txt"
